### ISSUE TITLE
Recommended way to include images in tool help and README

### ISSUE THREAD

**Issue by peterjc** [galaxy-iuc/standards#12]
I would like to include images in _both_ the `<help>` tool text RST, and also the repository's `README.rst` file. This is particularly useful for tools producing graphical output in order to document the expected output, e.g.
- https://github.com/peterjc/pico_galaxy/tree/master/tools/mummer
- https://github.com/peterjc/pico_galaxy/tree/master/tools/venn_list

Where should images best be put relative to the `README.rst` and/or `example_tool.xml` files?

Here's some devteam and IUC examples using images within the tool help - but currently missing a `README.rst` file:
- https://github.com/galaxyproject/tools-iuc/blob/master/tools/bedtools/closestBed.xml
- https://github.com/galaxyproject/tools-devteam/blob/master/tools/weblogo3/rgWebLogo3.xml

e.g.

```
.. image:: $PATH_TO_IMAGES/closest-glyph.png
```

**Comment by peterjc** [comment]
See also: https://wiki.galaxyproject.org/DefiningImagesInToolConfigs which says:

_Tool configuration files included in repositories in the tool shed that display images in the tool's help section define the images using any of the following example definitions.  The previously required `$PATH_TO_IMAGES` is now deprecated, and is ignored if used.  The "best practice" for including image files within the repository is to place them in the directory path <repository root>/static/images within the repository hierarchy in the tool shed._

**Comment by bgruening** [comment]
As you quoted, I think we need to keep them in `/static/images` if we want to use them from the TS.

**Comment by peterjc** [comment]
So we should use `{tar-ball-root}/static/images/example.png` which would be accessed in the `<help>` as just:

```
.. image:: example.png
```

While in `{tar-ball-root}/README.rst` to get it to display nicely on GitHub you would use:

```
.. image:: static/images/example.png
```

Would that work on the Tool Shed?

What about for the `{tar-ball-root}/tools/my_tool/README.rst` style? This implies having to use a shared top level images folder, and that I need to use the relative path `../../static/images/example.png` here?

**Comment by bgruening** [comment]
I think the `/static/images` is relative to your `tool.xml` file, isn't it?

**Comment by peterjc** [comment]
I'm unclear from the wiki if `static/images/` is relative to the tar-ball root, or the `README.rst`, or the `example_tool.xml` - it looks like some experimentation will be needed.

**Comment by bgruening** [comment]
@peterjc the modern way is `.. image:: single-filter.png` where the location of the image is not strictly defined as far as I know.
It can be `./static/images` but also `./images` as used in https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/bamtools/bamtools_filter/images

**Comment by hexylena** [comment]
Mentioned this in the big PR. Please see if that documentation was OK.

**Comment by bgruening** [comment]
@erasche this is super. Just wanted to update this PR. Peter can we close this?

**Comment by peterjc** [comment]
New text from @erasche reads:

```
Including Images
^^^^^^^^^^^^^^^^

If you've produced images detailing how your tool works (e.g. `bedtools`_), it
might be nice for those images to be included in the Galaxy tool documentation!

Images should be placed in a subdirectory, ``./static/images/``, and referenced
in your tool help as ``.. image:: my-picture.png``.
```

This isn't 100% clear to me - what is this path relative too? The tool's XML file this RST help text is written in? Or the `README.rst` which might be in a different folder?

I would suggest the tree structure in https://github.com/galaxy-iuc/standards/blob/master/docs/best_practices/repositories.rst include an example `.../static/images/` folder to help clarify this.

**Comment by hexylena** [comment]
@peterjc sure, you're right. Not 100% clear. I'll try and add some more examples/details here soon.
