### ISSUE TITLE
Conventions for tool collections and suites

### ISSUE THREAD

**Issue by peterjc** [galaxy-iuc/standards#19]
Currently https://github.com/galaxy-iuc/standards/blob/master/docs/best_practices/repositories.rst only talks about top level folders for `tools/`, `packages/`, `data_managers`, and sometimes `visualizations/` and `datatypes/`.

In https://github.com/galaxyproject/tools-devteam and https://github.com/galaxyproject/tools-iuc this is supplemented by `suites/` and `tool_collections/`.

When a suite covers a broad range of tools from different authors having `suites/` as a top level folder makes sense. I'm not so sure about the `tool_collections/` folder.

**Comment by peterjc** [comment]
Consider examples like bedtools (multiple closely related tools from the same team).

To me this feels like it needlessly separates all the pieces. Here https://github.com/galaxyproject/tools-devteam/blob/master/suites/suite_bamtools_2_3_0 points to the three tools under https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/bamtools

Note there is nothing under the tool level `tools/` folder for bedtools - which I have found confusing when browsing the repository for a particular tool (but searching works).

.. code::

```
tools-devteam/
├── ...
├── tools/
│   └── ...
├── suites/
│   ├── suite_bamtools_2_3_0/
│   └── ...
└── tool_collections/
    ├── ...
    └── bedtools
        ├── bedtools/
        ├── bedtools_filter/
        └── bedtools_split/
```

Would something like this work instead of `tool_collections/` perhaps?

.. code::

```
tools-devteam/
├── ...
└── tools/
    ├── ...
    └── bedtools
        ├── suite_bamtools_2_3_0/
        ├── bedtools/
        ├── bedtools_filter/
        └── bedtools_split/
```

**Comment by blankenberg** [comment]
I'm also do not like the separate `tool_collections directory`. I think that your proposed structure under tools/ seems logical and is how I have been doing vegan: https://github.com/galaxyproject/tools-iuc/tree/master/tools/vegan, with additional `macros` and `test-data` folders for shared content (no suite exists for vegan yet).

**Comment by bgruening** [comment]
I think the entire concept of `tool_collections` is deprecated. With planemo and the de-multiplexing feature it should be possible to have `./tools/bedtools/` like we have now and create separate repositories with planemo.
I don't like too many folders and hierarchies.

**Comment by hexylena** [comment]
Yep, :-1: to tool_collections directories. As long as suites directory is JUST meta packages and no code, I'm fine with that.

**Comment by peterjc** [comment]
Where can I read more about planemo de-multiplexing (multiple tool shed repositories/packages from a single `.shed.yml` file)? Is there a planemo PR or issue on this @jmchilton other than #6 for general `.shed.yml` documentation?

Also yes, I'm happy with `suites/` if it is used for meta-packages only.

**Comment by hexylena** [comment]
@peterjc https://github.com/galaxyproject/planemo/pull/143 I believe

**Comment by jmchilton** [comment]
I will document the de-multiplexing in galaxyproject/planemo#143 when someone commits to using it :). I have not quite sold @blankenberg yet that it is better than just maintaining a directory per tool is better. My biggest argument against the directory per tool thing is just that noone is doing it despite everyone agreeing it would be the best practice. The hope with de-multiplexing is to have the same end result in a way that people would actually be willing to us.

**Comment by bgruening** [comment]
I would use this for new tool suites, not sure about old once - we do not have a migration path for it now.
I think multiple folders are a unneeded overhead for developers.

**Comment by hexylena** [comment]
Since the original release of hmmer3 was broken due to installation issues, I'll commit to using it here and now. :) I'll push a demultiplexed version to the MTS this afternoon.

**Comment by blankenberg** [comment]
Once the demultiplexed stuff is all working well, I can be convinced that one directory is a good direction. I'll go ahead and flatten vegan at that point.

**Comment by hexylena** [comment]
@blankenberg demultiplexing is working as of the latest planemo. You can see it on the TTS [here](https://testtoolshed.g2.bx.psu.edu/repository/browse_repositories?async=false&sort=name&page=1&show_item_checkboxes=false&advanced_search=false&f-free-text-search=&f-free-text-search=hmmer). I've been very happy with it for all 1 of my packages.

**Comment by hexylena** [comment]
Also updated PR with new docs regarding this
