### ISSUE TITLE
Document exit code detection

### ISSUE THREAD

**Issue by hexylena** [galaxy-iuc/standards#20]
Also CC to wiki

**Comment by peterjc** [comment]
Good point - currently missing on https://github.com/galaxy-iuc/standards/blob/master/docs/best_practices/tool_xml.rst

What did you mean about the wiki? The `<stdio>`, `<regex>` and `<exit_code> tag sets` are listed on http://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax

**Comment by hexylena** [comment]
@peterjc I meant the use of https://github.com/galaxyproject/galaxy/pull/117

**Comment by peterjc** [comment]
Thanks - I missed `<command detect_errors="aggressive">` etc being merged into Galaxy, I'll start using that assuming it is already in the stable release.

**Comment by hexylena** [comment]
Yep, been there since pre-GCC. It wasn't a lot of noise made, as seems typical of some of these really great features that get added (e.g. sections).

My undergrads are working on Galaxy tools so hopefully I'll find time to update docs.
