### ISSUE TITLE
Checklists for tool integration

### ISSUE THREAD

**Issue by bebatut** [galaxy-iuc/standards#24]
Hi,

With the french community, we proposed some checklists to develop wrappers and integrate them in a ToolShed.

_General things before toolShedization_:
- Creation of a github repo for wrappers or use an existing repository.
- Create a `tools` directory for the tools.
- Create a `packages` directory for the packages
- Install `planemo` with `pip install planemo`
- Configure a shed account with  `planemo config_init` and editing the `~/.planemo.yml` file

_Wrapper creation for a tool_:
- Configure the environment with above checklist
- Create a directory with tool name
- Create the `tool_name.xml` file with `planemo tool_init --id 'tool_name' --name 'Tool description'`
- Fill the `tool_name.xml` by checking the [Best Practices](http://galaxy-iuc-standards.readthedocs.org/en/latest/best_practices.html)
- Add `tool_dependencies.xml` file
- Fill `requirements` section in `tool_name.xml` with link to `packages` in `tool_dependencies.xml`
- Add `test-data` directory
- Fill `test-data` directory with at least one input file and the expected output file
- Fill the `tests` section in `tool_name.xml` file
- (If specific data are needed) Add `tool-data` directory
- (If specific data are needed) Add `data_name.loc.sample` file in `tool-data` directory with description of the data
- (If specific data are needed) Add `tool_data_table_conf.xml.sample` file with link to `.loc.sample` files in `tool-data` directory
- Check `tool_name.xml` with `planemo lint`
- Run functional tests of the tool in a local Galaxy with `planemo test --galaxy_root=/path/to/galaxy`
- Serve the tool on a local Galaxy instance with `planemo serve --galaxy_root=/path/to/galaxy`
- Test the tool on the local Galaxy instance

_ToolShedization of a tool or dependency package not for IUC GitHub repository_:
- Create the wrapper with above checklist
- Define the repository name by checking the [note on naming convention](https://planemo.readthedocs.org/en/latest/publishing.html#creating-a-repository)
- Create a shed repository with `planemo shed_init --name=<name> --owner=<shed_username> --description=<short description>`
- Edit the `.shed.yml` file
- Check the `.shed.yml` file with `planemo shed_lint`
- Create the remote repository with `planemo shed_create --shed_target shed_name`
- (If changes) Update the shed repository with `planemo shed_update --shed_target`

_ToolShedization of a tool or dependency package for a IUC GitHub repository_:
- Create an [issue on IUC GitHub](https://github.com/galaxyproject/tools-iuc/issues)
- Fork [IUC GitHub](https://github.com/galaxyproject/tools-iuc) on your GitHub account
- Clone of the corresponding repository `git clone tools-iuc name_of_repository_you_want`
- Go to the corresponding repository
- Create a branch to develop the tool `git checkout -b name_of_tool_to_develop`
- Develop the tool or package (at least `tool_dependencies.xml` for package, check ToolShedization of a tool for more detail)
- Commit the changes with atomic commit `git commit`
- Deploy it on a ToolShed (local or test ToolShed)
- Install it on a local Galaxy instance
- Test installation on local Galaxy instance
- Push the changes `git push origin name_of_tool_to_develop`
- Go to the github repository
- Check on 'Compare & Pull Request'
- Add general comment on what is content the Pull Request
- Wait review

What do you think of these checklists ? Could they be integrated somewhere?

**Comment by hexylena** [comment]
Yes! Awesome. I'll work on getting those into a PR form later this week. Thanks @bebatut :)
