### ISSUE TITLE
IUC Needs a Logo

### ISSUE THREAD

**Issue by hexylena** [galaxy-iuc/standards#28]

**Comment by peterjc** [comment]
There was the shield design Martin Page made for the GCC2015 hackathon T-shirts - looking back on old emails he sounded willing to make it into a logo for us back in September 2015, although he was a little busy at the time and we didn't follow up on it. Shall we ask him again now?

**Comment by hexylena** [comment]
@peterjc :+1: sounds great!

**Comment by peterjc** [comment]
Thread resurrected on the IUC mailing list...

**Comment by hexylena** [comment]
Cheers mate.

**Comment by bgruening** [comment]
Can we have something like this: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Gnome-preferences-other.svg/768px-Gnome-preferences-other.svg.png

**Comment by yhoogstrate** [comment]
@bebatut I believe you are the right person to close this issue

**Comment by bebatut** [comment]
I will @yhoogstrate 😄
