### ISSUE TITLE
Pick a desired order for configfiles

### ISSUE THREAD

**Issue by jmchilton** [galaxy-iuc/standards#3]
See also https://github.com/galaxyproject/planemo/issues/132

**Comment by hexylena** [comment]
Status Quo:

Devteam tools:

| after | before | count |
| --- | --- | --- |
| inputs | outputs | 5 |
| outputs | tests | 2 |
| tests | help | 2 |
| help |  | 1 |

IUC tools:

| after | before | count |
| --- | --- | --- |
| inputs | outputs | 1 |
| outputs | tests | 1 |
| tests | help | 1 |
| help |  | 2 |

Personally I'm fond of after inputs or after outputs.

**Comment by bgruening** [comment]
After inputs, before outputs ... it is an `input` :)

**Comment by jmchilton** [comment]
Given the counts I am :+1: for after `<inputs>`

**Comment by hexylena** [comment]
Sounds good to me! (but let's leave this open another 19 hours for comment)

**Comment by peterjc** [comment]
I don't like `<inputs>`, `<configfiles>`, `<outputs>`. I prefer having inputs then outputs right next to each other - they are both listing files consumed/produced by the tool, and as the name implies, it seems natural to have them next to each other.

For MIRA4 I put the `<configfiles>` after the `<outputs>`: https://github.com/peterjc/pico_galaxy/tree/master/tools/mira4_assembler - looking back I probably followed one of the core tools.

There is something to be said for putting this right after the `<command>` tag, that would be my second choice.

**Comment by bgruening** [comment]
But `<configfiles>` is also one consumed file, it's an `input`. I would like to see it next to input, above or before. @peterjc any reasoning for `after output`?

**Comment by peterjc** [comment]
Hmm. I see what you mean. What about `<command>`,  `<configfiles>`, `<inputs>`, `<outputs>`? It seems logical to me, but none of the tools already do this do they?

(I appear to be in a minority of one, so if there are no other suggestions, `<command>`,  `<inputs>`, `<configfiles>`, `<outputs>` looks like the consensus - I don't mind adopting this)

**Comment by bgruening** [comment]
No tool I know uses `<command>, <configfiles>, <inputs>, <outputs>`, but we can make them to use it :)

**Comment by nsoranzo** [comment]
I don't have a clear preference, but take into account that also variables for output `data` can be used inside a `<configfile>`, see for example https://github.com/galaxyproject/galaxy/blob/dev/tools/plotting/boxplot.xml

**Comment by peterjc** [comment]
Yes - just like the `<command>` tag uses both inputs and outputs.

**Comment by nsoranzo** [comment]
@peterjc ...and configfiles!

**Comment by peterjc** [comment]
Yes. This is an argument for putting `<command>` and `<configfiles>` next to each other. Also it is quite a common pattern the that command is essentially just "run this job" where the job is defined by the configuration file. e.g. MIRA4 and its manifest files, or the boxplot tool calling gnuplot with a file of plotting commands.

**Comment by jmchilton** [comment]
I was initially swayed by the numbers (as I had indicated) - but I must admit I am swayed by the logic of `command`, `configfiles`, `inputs`, `outputs`. Switching my vote (do non-iuc members get to vote on these things?).

**Comment by peterjc** [comment]
We co-opted you into the IUC during GCC2013 in Oslo didn't we John? I think there was a group photo as proof...

@erasche @nsoranzo what do you think of `command`, `configfiles`, `inputs`, `outputs` as the preferred order?

**Comment by nsoranzo** [comment]
Inputs and outputs go inside configfiles; inputs, outputs and configfiles go inside command. So my logic would say `inputs`, `outputs`, `configfiles`, `command`, but traditionally `command` is above...

This makes me think if it does really make sense to discuss an order and especially to "force" it with `planemo lint`.

**Comment by peterjc** [comment]
I like `inputs`, `outputs`, `configfiles`, `command` too, but as you note, traditionally `command` has been first - it would be a lot of upheaval to change that now.

Linting is optional, but a consistent ordering will make life easier in the long run.

**Comment by jmchilton** [comment]
@nsoranzo I have considered adding a flag for the linting formatting issues like this - no desire to bully people with planemo  - on this anyway :).

**Comment by nsoranzo** [comment]
@jmchilton :+1: for the flag!

**Comment by hexylena** [comment]
I'm starting to like `command, configfiles, inputs, outputs`, since configfiles is really just an abused command section.

**Comment by blankenberg** [comment]
One thing nice about configfiles coming nearer to the end is that they can sometimes be large and opening up a tool conf, you usually want to see the tool id/name, the command, then the user input stuff, then defined outputs/configfiles or configfiles/outputs, at least in the case when it is actually a _config file_, and not just e.g. a shell script that you end up calling as `<command>sh $config_file</command>`

**Comment by nsoranzo** [comment]
I think command and configfiles are similar in this respect, so they should go together either at the start or at the end.

**Comment by hexylena** [comment]
e.g. like [MIRA](https://github.com/peterjc/pico_galaxy/blob/3a9e657377bc99c06b85b1b12e09d7269de18184/tools/mira4_assembler/mira4_de_novo.xml)

**Comment by hexylena** [comment]
Votes:

| Position | Tally |
| --- | --- |
| `command, configfiles, inputs, outputs` | @erasche @nsoranzo @bgruening @jmchilton @peterjc |
| `command, inputs, outputs, configfiles` | @blankenberg |

@jmchilton "do non-members get a vote", I believe they do, since devteam takes IUC's opinions into account. 

[Peter: Moved myself in the table to reflect my preference between these options]

**Comment by hexylena** [comment]
Okay, overwhelming support is in favour of `command, configfiles, inputs, outputs`. I'll update the documentation to reflect this.
