### ISSUE TITLE
Specify README best practices.

### ISSUE THREAD

**Issue by jmchilton** [galaxy-iuc/standards#4]
Background: https://github.com/galaxyproject/planemo/issues/89

My proposal would be:

"Every unrestricted tool shed repository should contain a `README` file (if plain text) or `README.rst` (if rST). The Tool Shed recognizes many more types of readme files than this - but these are not encourage and may be deprecated in the future."

**Comment by peterjc** [comment]
I'd turn it round and put `README.rst` first as the preferred way of doing things.

Also do you mean `README` (no extension) or `README.txt` if plain text? The Tool Shed and GitHub accept both - not sure which is more common.

**Comment by nsoranzo** [comment]
@jmchilton s/rST/[reStructuredText](http://docutils.sourceforge.net/rst.html)/ and s/encourage/encouraged/ .

@peterjc I think `README` is more common in Unix-like land, `README.txt` in Windows.

**Comment by peterjc** [comment]
I meant which is more common on the Tool Shed so far: `README` (Unix style) or `README.txt` (DOS/Windows style)?

**Comment by jmchilton** [comment]
Update: Thanks for the feedback all - how about this:

"Every unrestricted tool shed repository should contain a [README](http://en.wikipedia.org/wiki/README) file - named either `README` or `README.txt` (if plain text) or `README.rst` (if [reStructuredText](http://docutils.sourceforge.net/rst.html)). A reStructuredText `README.rst` is generally preferred. For a good example of such a file - please see Peter Cock's NCBI Blast+ Suite's [README.rst](https://github.com/peterjc/galaxy_blast/blob/master/tools/ncbi_blast_plus/README.rst).

The Tool Shed recognizes many more types of README files than this - but these are not encouraged and may be deprecated in the future. [Markdown](https://help.github.com/articles/github-flavored-markdown/) is not supported by the Tool Shed at this time and so `README.md` are not recognized at all."

See also:
- https://github.com/galaxyproject/planemo/commit/d26929e18bbd61f43650336f02a70f2899f5b63b 
- galaxyproject/planemo#134

Another Update: slight wording improvement.

**Comment by bgruening** [comment]
:+1:

**Comment by hexylena** [comment]
:+1:

**Comment by hexylena** [comment]
Open a PR @jmchilton :)
