### ISSUE TITLE
Tool dependency packages section out of date

### ISSUE THREAD

**Issue by elichad** [galaxy-iuc/standards#70]
https://github.com/galaxy-iuc/standards/blob/master/docs/best_practices/tool_xml.rst#tool-dependency-package

> If you are using perl/ruby/python/R packages, use the corresponding `*_environment` tags to depend on a specific version of Perl/Ruby ...

1. I think this section is out of date. I can't find any `*_environment` tags in the tool docs except `set_environment` which is ignored by conda anyway, and it looks like the currently recommended syntax is more like `<requirement type="package" version="2.15.1">R</requirement>`
2. Is this a 'can' or 'should' piece of guidance? e.g. if my packages support all current versions of Python, should I still specify a particular version?

**Comment by nsoranzo** [comment]
Thanks @elichad for reporting the issue!
1) Yes, I'll open a PR to remove that section
2) If your requirement is a Python/R/... package, you don't usually need to specify an additional requirement for the language version. If instead you are shipping a script with your tool, it's recommended to add a `<requirement />` for the language with a version.

Hope that helps!
